language: go

go:
  - 1.11.x

git:
  depth: 1

before_script:
  - curl https://glide.sh/get | sh
  - glide install
  - cp .env.example .env
  - cp .env.example .env.testing

script:
  - go test ./tests/main_test.go